# Annex III high-risk categories keywords
biometric_identification:
  - biometric
  - "face recognition"
  - fingerprint
  - iris
critical_infrastructure:
  - "power grid"
  - "water supply"
  - transport
education:
  - exam
  - grading
  - admission
employment:
  - hiring
  - recruitment
  - promotion
public_services:
  - "social security"
  - benefit
  - credit
law_enforcement:
  - crime
  - police
  - investigation
migration:
  - asylum
  - visa
  - "border control"
judicial:
  - court
  - judge
  - legal
