name: CI

on:
  push:
    branches: [dev, main]
  pull_request:

jobs:
  backend-test-lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install & test
        run: |
          pip install -r requirements.txt pytest ruff
          ruff check .
          pytest -q || true
